sudo: required
services:
        - docker

before_install:
        - docker build -t sundayanirut/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true sundayanirut/react-test npm test

after_success:
        - docker build -t sundayanirut/multi-client ./client
        - docker build -t sundayanirut/multi-nginx ./nginx
        - docker build -t sundayanirut/multi-server ./server
        - docker build -t sundayanirut/multi-worker ./worker
          # Log in to the docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
          #Take those images and push them to docker hub
        - docker push sundayanirut/multi-client
        - docker push sundayanirut/multi-nginx
        - docker push sundayanirut/multi-server
        - docker push sundayanirut/multi-worker
